# -*- coding: utf-8 -*-
"""BOT DISCORD Ismael Saad Yassine Octave.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qAQT9UgVOQ0L3WyBFpKEAh48tceoG7yl
"""

!pip install discord.py
!pip install nest_asyncio

#Ismaël Saad Yassine Octave:
import nest_asyncio 
nest_asyncio.apply()
import discord 
import random

intents = discord.Intents.all()
intents.messages = True
intents.members = True
intents.typing = True
client = discord.Client(intents=intents)
score = 0
@client.event
async def on_ready():
    print("Le bot est prêt !")

"""@client.event
async def on_typing(channel, user, when):
     await channel.send(user.name+" écrit super lentement")"""

@client.event
async def on_member_join(member):
    general_channel = client.get_channel(1047069511217598498)
    await general_channel.send("Bienvenue sur le serveur ! "+ member.name)
i=0
score = 0
@client.event
async def on_message(message):
  message.content = message.content.lower() 
  if message.author == client.user:
    return
  #fonction permettant d'avoir la liste de toutes les commandes du bot
  if "!help" in message.content:
    await message.channel.send("**Voici les commandes du bot Discord !**\nPour commencer le quizz sur la Coupe du Monde 2022 et connaître les commandes : **!quizz**\nPour avoir les resultats de la coupe du monde : **!resultats**\nPour recevoir vos meilleurs GIFs : **!gif**\nPour écouter mes recommandations musicales : **!musique**\nPour avoir une blague : **!blague**")
  #fonction permettant d'avoir la liste de toutes les commandes concernant les résultats de la Coupe du monde
  if "!resultats" in message.content:
    await message.channel.send("**Voici les commandes pour avoir les resultats de la Coupe du Monde 2022 !**\n**!groupe** pour voir tous les resultats des __poules__ !\n**!huitieme** pour voir les resultats des __huitièmes de finale__ !\n**!quart** pour voir tous les resultats des __quarts de finale__ !")
  #Quizz sur la Coupe du monde
  if "!quizz" in message.content:  
    global score, i
    await message.channel.send("C'est parti pour une série de __5 questions__ sur la coupe du monde \n\n")
    await message.channel.send("Pour avoir un indice : **!indice** \nSi vous bloquez sur une question : **!skip** \n\nLe quizz est noté sur **10 points**,\nÀ chaque indice demandé vous perdez **1 point**.\nÀ chaque bonne réponse (sans indice) vous gagnerez **2 points**.\n")
    await message.channel.send("Quand vous êtes prêt à commencer : tapez **!pret**")
  if "!pret" in message.content:
    await message.channel.send("Première question : Quel joueur de la coupe du monde a égalisé le record de but de Thierry Henry pendant cette coupe du monde ?")
    i =  i + 1
  
  elif i==1:
    if "giroud" in message.content:
      score = score+2
      await message.channel.send("Bravo ! Bonne réponse ! (+2 points)")
      await message.channel.send("https://tenor.com/view/%D8%AC%D9%8A%D8%B1%D9%88-oliver-oliver-giroud-giroud-milan-gif-24842349")
      await message.channel.send("Votre score est de " + str(score))
      await message.channel.send("Question 2 : Quelle équipe a gagné son match de 7 buts à 0 pendant cette coupe du monde ?")
      i = i + 1
    elif "indice" in message.content:
      score = score - 1
      await message.channel.send("Il est sous coté -1 points")
      await message.channel.send("Votre score est de " + str(score))
    elif "skip" in message.content:
      await message.channel.send("La bonne réponse était Olivier Giroud")
      await message.channel.send("Votre score est de " + str(score))
      await message.channel.send("Question 2 : Quelle équipe a gagné son match de 7 buts à 0 pendant cette coupe du monde ?")
      i = i + 1
    else:
      await message.channel.send("Ce n'est pas la bonne réponse veuillez retenter")

  elif i==2:
    if "espagne" in message.content:
      score = score + 2
      await message.channel.send("Bravo ! Bonne réponse ! (+2 points)")
      await message.channel.send("https://tenor.com/view/tmzka-sergio-ramos-sr4-ramos-spain-nt-gif-17736772")
      await message.channel.send("Votre score est de " + str(score))
      await message.channel.send("Question 3 : Quel maillot a été élu le plus beau durant cette coupe du monde ?")
      i = i + 1
    elif "indice" in message.content:
      score = score - 1
      await message.channel.send("https://tenor.com/view/menemen-yumurta-yemek-gif-11572712")
      await message.channel.send("Me gusta la corida, -1 point")
      await message.channel.send("Votre score est de " + str(score))
    elif "skip" in message.content:
      await message.channel.send("La bonne réponse était l'Espagne")
      await message.channel.send("Votre score est de " + str(score))
      await message.channel.send("Question 3 : Quel maillot a été élu le plus beau durant cette coupe du monde ?")
      i = i + 1
    else:
      await message.channel.send("Ce n'est pas la bonne réponse veuillez retenter")

  elif i==3:
    if "japon" in message.content:
      score = score + 2
      await message.channel.send("Bravo ! Bonne réponse ! (+2 points)")
      await message.channel.send("Votre score est de " + str(score))
      await message.channel.send("https://tenor.com/view/asain-japan-gif-19431061")
      await message.channel.send("Question 4 : Quelle est la première équipe ayant subi une défaite pendant cette coupe du monde ?")
      i = i + 1
    elif "indice" in message.content:
      score = score - 1
      await message.channel.send("Projet blue lock, -1 point")
      await message.channel.send("https://tenor.com/view/blue-lock-isagi-anime-gif-21590662")
      await message.channel.send("Votre score est de " + str(score))
    elif "skip" in message.content:
      await message.channel.send("La réponse était le maillot du Japon")
      await message.channel.send("Votre score est de " + str(score))
      await message.channel.send("Question 4 : Quelle est la première équipe ayant subi une défaite pendant cette coupe du monde ?")
      i = i + 1
    else:
      await message.channel.send("Ce n'est pas la bonne réponse veuillez retenter")

  elif i==4:
    if "qatar" in message.content:
      score = score + 2
      await message.channel.send("Bravo ! Bonne réponse ! (+2 points)")
      await message.channel.send("Votre score est de " + str(score))
      await message.channel.send("https://tenor.com/view/%D8%AA%D9%85%D9%8A%D9%85-%D9%82%D8%B7%D8%B1-%D8%A7%D9%84%D8%AF%D9%88%D8%AD%D9%87-%D9%A2%D9%A0%D9%A2%D9%A2-qatar-gif-14922196")
      await message.channel.send("Question 5 : Quel pays a remporté le plus de coupe du monde ?")
      i = i + 1
    elif "indice" in message.content:
      score = score - 1
      await message.channel.send("Surnom : Al-Annabi, -1 point")
      await message.channel.send("https://tenor.com/view/%D9%84%D8%B9%D9%91%D9%8A%D8%A8-laeeb-gif-25275534")
      await message.channel.send("Votre score est de " + str(score))
    elif "skip" in message.content:
      await message.channel.send("La réponse était l'équipe du Qatar")
      await message.channel.send("Votre score est de " + str(score))
      await message.channel.send("Question 5 : Quel pays a remporté le plus de coupe du monde ?")
      i = i + 1
    else:
      await message.channel.send("Ce n'est pas la bonne réponse veuillez retenter")
      
  elif i==5:
    if "bresil" in message.content:
      score = score + 2
      await message.channel.send("Bravo ! Bonne réponse ! (+2 points)")
      await message.channel.send("Votre score final est de " + str(score))
      await message.channel.send("https://tenor.com/view/vini-neymar-paqueta-dance-brazil-brazil-football-goal-gif-25209715")
      i = i + 1
    elif "indice" in message.content:
      score = score - 1
      await message.channel.send("Obrigado Rodizio, -1 point")
      await message.channel.send("https://tenor.com/view/jesus-hesus-christ-rio-de-janeiro-religion-gif-7944393")
      await message.channel.send("Votre score est de " + str(score))
    elif "skip" in message.content:
      await message.channel.send("Dommage, c'était le Brésil !")
      await message.channel.send("Score final : " + str(score))
    else:
      await message.channel.send("Ce n'est pas la bonne réponse veuillez retenter")
  #fonction permettant d'avoir les résultats de la phase de groupe de la Coupe du monde
  elif "!groupe" in message.content:  
    await message.channel.send("Voici les équipes ayant passée la phase des poules\n")
    await message.channel.send("--------------------------------------------------------")

    await message.channel.send("**GROUPE A**")  
    await message.channel.send("1- Pays Bas :flag_nl: ")
    await message.channel.send("2- Senegal :flag_sn: ")

    await message.channel.send("**GROUPE B**")  
    await message.channel.send("1- Angleterre :flag_gb: ")
    await message.channel.send("2- USA :flag_us: ")

    await message.channel.send("**GROUPE C**")  
    await message.channel.send("1- Argentine :flag_ar: ")
    await message.channel.send("2- Pologne :flag_pl: ")

    await message.channel.send("**GROUPE D**")  
    await message.channel.send("1- France :flag_fr:")
    await message.channel.send("2- Australie :flag_au: ")

    await message.channel.send("**GROUPE E**")  
    await message.channel.send("1- Japon :flag_jp: ")
    await message.channel.send("2- Espagne :flag_es: ")

    await message.channel.send("**GROUPE F**")  
    await message.channel.send("1- Maroc :flag_ma: ")
    await message.channel.send("2- Croatie :flag_hr: ")

    await message.channel.send("**GROUPE G**")  
    await message.channel.send("1- Brésil :flag_br: ")
    await message.channel.send("2- Suisse :flag_ch: ")

    await message.channel.send("**GROUPE H**")  
    await message.channel.send("1- Portugal :flag_pt: ")
    await message.channel.send("2- Corée du Sud :flag_kr: ")
  #fonction permettant d'avoir les résultats des matchs de quart de finales de la coupe du monde
  elif "!quart" in message.content: 
    await message.channel.send("Voici les équipes ayant gagné leur match de quart de finale:\n")
    await message.channel.send("--------------------------------------------------------")

    await message.channel.send("France :flag_fr: 2-1 Angleterre :flag_gb:")
    await message.channel.send("-----------------")
    
    await message.channel.send("Maroc :flag_ma: 1-0 Portugal :flag_pt:")
    await message.channel.send("-----------------")

    await message.channel.send("Argentine :flag_ar: 2 - 2 Pays-Bas :flag_nl: |  (4 - 3 aux tirs au buts)")
    await message.channel.send("-----------------")

    await message.channel.send("Croatie :flag_hr: 1 - 1 Brésil :flag_br: |  (4 - 2 aux tirs au buts)")
    await message.channel.send("-----------------")
  #fonction permettant d'avoir les résultats des matchs de huitieme de finales de la coupe du monde
  elif "!huitieme" in message.content:
    await message.channel.send("Voici le résultat des matchs joué pendant la phase de huitième de finale:\n")

    await message.channel.send("France :flag_fr: 3 - 1 Pologne :flag_pl:")
    await message.channel.send("-----------------------")

    await message.channel.send("Maroc :flag_ma: 0 - 0 Espagne :flag_es: |  (3 - 0 aux tirs au buts)")
    await message.channel.send("-----------------------")

    await message.channel.send("Portugal :flag_pt: 6 - 1 Suisse :flag_ch:")
    await message.channel.send("-----------------------")

    await message.channel.send("Brésil :flag_br: 4 - 1 Corée du Sud :flag_kr:")
    await message.channel.send("-----------------------")

    await message.channel.send("Argentine :flag_ar: 2 - 1 Australie :flag_au:")
    await message.channel.send("-----------------------")

    await message.channel.send("Pays-Bas :flag_nl: 3 - 1 Etat-Unis :flag_us:")
    await message.channel.send("-----------------------")

    await message.channel.send("Angleterre :flag_gb: 3 - 0 Sénégal :flag_sn:")
    await message.channel.send("-----------------------")

    await message.channel.send("Japon :flag_jp: 1 - 1 Croatie :flag_hr: |  (1 - 3 aux tirs au buts)")
    await message.channel.send("-----------------------")
  #Modération d'insulte sur le discord  
  elif "fdp" in message.content:
    await message.channel.send("C'est pas très poli, veuillez surveillez votre language ou un modérateur s'occupera de vous")
  elif "nique ta mere" in message.content:
    await message.channel.send("C'est pas très poli, veuillez surveillez votre language ou un modérateur s'occupera de vous")
  elif "je te pisse dessus" in message.content:
    await message.channel.send("C'est pas très poli, veuillez surveillez votre language ou un modérateur s'occupera de vous")
  elif "ferme ta gueule" in message.content:
    await message.channel.send("C'est pas très poli, veuillez surveillez votre language ou un modérateur s'occupera de vous")
  elif "pd" in message.content:
    await message.channel.send("C'est pas très poli, veuillez surveillez votre language ou un modérateur s'occupera de vous")
  elif "ta meme pas de mcdo chez toi" in message.content:
    await message.channel.send("C'est pas très poli, veuillez surveillez votre language ou un modérateur s'occupera de vous")
  elif "enculé" in message.content:
    await message.channel.send("C'est pas très poli, veuillez surveillez votre language ou un modérateur s'occupera de vous")
  elif "sale chien" in message.content:
    await message.channel.send("C'est pas très poli, veuillez surveillez votre language ou un modérateur s'occupera de vous")
  elif "ntm" in message.content:
    await message.channel.send("C'est pas très poli, veuillez surveillez votre language ou un modérateur s'occupera de vous")
  elif "fils de pute" in message.content:
    await message.channel.send("C'est pas très poli, veuillez surveillez votre language ou un modérateur s'occupera de vous")
  elif "enflure" in message.content:
    await message.channel.send("C'est pas très poli, veuillez surveillez votre language ou un modérateur s'occupera de vous")
  #fonction permettant d'obtenir une blague de manière aléatoire
  elif "!blague" in message.content:
    b = random.randint(1,10)
    if b == 1:
      await message.channel.send("Pourquoi quand on veut viser on ferme un œil ? Car si on fermait les deux on verrait plus rien !")
      await message.channel.send("https://tenor.com/view/hahahahah-gahahahaha-haha-ha-fun-gif-19042485")
    if b == 2:
      await message.channel.send("Pourquoi quand on veut viser on ferme un œil ? Car si on fermait les deux on verrait plus rien !")
      await message.channel.send("https://tenor.com/view/mr-bean-cestbon-bon-gif-5033885")
    if b == 3:
      await message.channel.send("C'est l'histoire d'un pingouin qui respire par les fesses Un jour il s’assoit et il meurt.")
      await message.channel.send("https://tenor.com/view/lol-mdr-gif-24349915")
    if b == 4:
      await message.channel.send("Pourquoi est-ce pénible de regarder du patinage artistique ? Parce que le patin agace.")
      await message.channel.send("https://tenor.com/view/zemmour-zemour-rire-le-z-ez-gif-23566100")
    if b == 5:
      await message.channel.send("Qu’est-ce qu’un nem avec des écouteurs ? Un nem P3.")
      await message.channel.send("https://tenor.com/view/risitas-dentadura-excited-happy-laugh-giggle-gif-13601656")
    if b == 6:
      await message.channel.send("Quel est le comble pour un joueur de bowling ? C’est de perdre la boule !")
      await message.channel.send("https://tenor.com/view/mister-v-scott-mister-v-marche-mister-v-modifie-gif-25169291")
    if b == 7:
      await message.channel.send("Quel métier les chiens peuvent-ils exercer ? Electrichien !")
      await message.channel.send("https://tenor.com/view/too-funny-funny-haha-laughing-rofl-gif-19178315")
    if b == 8:
      await message.channel.send("Que fait une vache avec une radio ? De la meuhsique !")
      await message.channel.send("https://tenor.com/view/lmao-laughing-hysterically-gif-26398146")
    if b == 9:
      await message.channel.send("Quel est le comble pour un marin ? Avoir le nez qui coule !")
      await message.channel.send("https://tenor.com/view/edouard-baer-il-est-genial-laughing-rire-gif-25072937")
    if b == 10:
      await message.channel.send("Connais-tu la blague de la chaise ? Elle est pliante !")
      await message.channel.send("https://tenor.com/view/belly-face-awesome-fat-funny-gif-3467111")
  #fonction permettant d'obtenir un gif de manière aléatoire
  elif "!gif" in message.content:
    g=random.randint(1,10)
    if g == 1:
      await message.channel.send("https://tenor.com/view/%E0%B8%AD%E0%B8%B9%E0%B9%89%E0%B8%A7-%E0%B8%81%E0%B8%AD%E0%B8%A5%E0%B9%8C%E0%B8%9F%E0%B8%9B%E0%B8%B4%E0%B8%87%E0%B8%9B%E0%B8%AD%E0%B8%87%E0%B8%98%E0%B8%87%E0%B8%8A%E0%B8%B1%E0%B8%A2-%E0%B9%84%E0%B8%94%E0%B8%AD%E0%B8%B2%E0%B8%A3%E0%B8%B5%E0%B9%88%E0%B8%95%E0%B8%B8%E0%B9%8A%E0%B8%94%E0%B9%84%E0%B8%A1%E0%B9%88%E0%B8%88%E0%B8%A3%E0%B8%B4%E0%B8%87%E0%B8%AB-%E0%B8%A7%E0%B9%89%E0%B8%B2%E0%B8%A7-%E0%B8%95%E0%B8%B7%E0%B9%88%E0%B8%99%E0%B9%80%E0%B8%95%E0%B9%89%E0%B8%99-gif-17828957")
    if g == 2:
      await message.channel.send("https://tenor.com/view/hahahahah-gahahahaha-haha-ha-fun-gif-19042485")     
    if g == 3:
      await message.channel.send("https://tenor.com/view/scared-im-gif-19003096")    
    if g == 4:
      await message.channel.send("https://tenor.com/view/hello-bonjour-gif-20115397")   
    if g == 5:
      await message.channel.send("https://tenor.com/view/girl-bye-im-out-bye-felicia-i-gotta-go-laters-gif-24880981")  
    if g == 6:
      await message.channel.send("https://tenor.com/view/fortnite-rollie-fortnite-dances-gif-25321329") 
    if g == 7:
      await message.channel.send("https://tenor.com/view/jim-carrey-oops-ouch-well-maybe-gif-15443300")
    if g == 8:
      await message.channel.send("https://tenor.com/view/mister-v-scott-mister-v-marche-mister-v-modifie-gif-25169291") 
    if g == 9:
      await message.channel.send("https://tenor.com/view/barry-and-iris-bwwm-kiss-wmbw-kiss-wmbw-love-bwwm-love-gif-23468130")
    if g == 10:
      await message.channel.send("https://tenor.com/view/reveluiv-woman-angry-throwing-stuff-gif-24980534")
      
  #fonction permettant d'avoir des recommendations musicale
  elif "!musique" in message.content:
    await message.channel.send("**!rap** pour écouter du rap\n**!citypop** pour écouter de la city pop\n**!popnfunk** pour écouter de la pop and funk\nChacune de ses commandes vous donnera un son en **aléatoire**, n'hésitez pas à la relancer plusieurs fois pour avoir d'autre musique...")
    z = 0
    w = 0
    x = 0
  elif "!rap" in message.content:
    z = random.randint(1, 3)
    if z == 1:
      await message.channel.send("https://youtu.be/-SHRul5e6ug%22%22")
      await message.channel.send("c'est pas ton pc qui glitch, SPK entre crochet près du name")
    if z == 2:
      await message.channel.send("https://youtu.be/lY9AK-cFDc8%22")
      await message.channel.send("la 808 réveille la voisine")
    if z == 3:
      await message.channel.send("https://youtu.be/gqBhF3sh7fk%22")
      await message.channel.send("comme des Qatari")

  elif "!citypop" in message.content:
    w = random.randint(1, 3)
    if w == 1:
      await message.channel.send("https://youtu.be/T_lC2O1oIew%22")
      await message.channel.send("le Miel")
    if w == 2:
      await message.channel.send("https://youtu.be/M0qMgoChzGI%22")
      await message.channel.send("Pour les amoureux")
    if w == 3:
      await message.channel.send("https://youtu.be/39JIOTr_Z_A%22")
      await message.channel.send("petite balade")

  elif "!pop" in message.content:
    x = random.randint(1, 3)
    if x == 1:
      await message.channel.send("https://youtu.be/wp43OdtAAkM%22")
      await message.channel.send("Les classiques")
    if x == 2:
      await message.channel.send("https://youtu.be/ImxVWBwUla0%22")
      await message.channel.send("good vibe")
    if x == 3: 
      await message.channel.send("https://youtu.be/BkKDSFYvxKU%22")
      await message.channel.send("Tu a du gout si tu a la ref")

client.run("MTA0NzA3MDEzMDQ4MTQwMTg1Ng.GY8Itm.6Jz2JSNCrCvpLya_6cPIkY3EiMRZG2RjfM2iCc")
#-------------------------------------------------------